import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from './components/appBar'
import { Grid, Box, TextField, Button} from '@mui/material';

import * as React from 'react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ResponsiveAppBar />
        <Box className={styles.titleDescription}>
          <Grid container spacing={0} sx={{marginLeft:'-20vw', marginTop:'10vw',width:'100%'}}>
            <Grid item xs={12}>
              <Box className={styles.title}>Instant colaborations <br /> for remote teams</Box>
                <br />
              <Box className={styles.para}>All in one for your remote team chats, <br /> collaboration and track projects</Box>
                <br/>
              <Box sx={{display:'flex', flexDirection:'row'}}>
                <TextField variant='filled' label="Email"/>
                <Button>Get early access</Button>
              </Box>
            </Grid>
          </Grid>
        </Box>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
